# we only need to point to python for the tests to run
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r unittests/requirements
  - pip install flake8

# command to run before the tests
before_script: 
  - "flake8 ahenkidentifier --ignore=E501,W291,W293"

# command to run tests
script: 
  - nosetests unittests/ahenk_test.py
